import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
//import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className='bg-red-100 h-screen'>
        <div className="bg-orange-300 flex justify-center h-32 text-5xl">
          <div className='my-auto'> hello, this is my app </div>
        </div>
        <div className=" flex justify-center">
        <div className="bg-slate-300 m-6 p-8 flex justify-center rounded-full">
         this is a button
        </div>
        </div>
      </div>
      </main>   
      
    </>
  )
}
